{
  # https://prettier.io/docs/en/options.html
  'printWidth': 120,
  'tabWidth': 2,
  'useTabs': false,
  'semi': true,
  'singleQuote': true,
  'trailingComma': 'es5',
	'bracketSpacing': true,
  'endOfLine': 'lf'
}