{
    # https://prettier.io/docs/en/options.html
    'printWidth': 120,
    'tabWidth': 4,
    'useTabs': true,
    'semi': true,
    'singleQuote': true,
    'trailingComma': 'es5',
    'bracketSpacing': true,
    'endOfLine': 'lf',
}
